// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTnst7w21DImBGHxFsJQ3-QMRNMCM6OXo',
    appId: '1:1052589681589:web:2c9d6b9be2ac3e8fc447fc',
    messagingSenderId: '1052589681589',
    projectId: 'fragrance-of-mastership',
    authDomain: 'fragrance-of-mastership.firebaseapp.com',
    storageBucket: 'fragrance-of-mastership.appspot.com',
    measurementId: 'G-B8ZEDJK5XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0S6BuFRlXOMhDOCNqg15sYls49W0iw08',
    appId: '1:1052589681589:android:077e0c420d62fb28c447fc',
    messagingSenderId: '1052589681589',
    projectId: 'fragrance-of-mastership',
    storageBucket: 'fragrance-of-mastership.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrw3sRvqWWuhu0LHPP7tGSx0TcmrlY8hs',
    appId: '1:1052589681589:ios:8457a3c8f04bc748c447fc',
    messagingSenderId: '1052589681589',
    projectId: 'fragrance-of-mastership',
    storageBucket: 'fragrance-of-mastership.appspot.com',
    iosClientId: '1052589681589-j0np6376p8u9gmtac35056tpo8c7hvv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fragrance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrw3sRvqWWuhu0LHPP7tGSx0TcmrlY8hs',
    appId: '1:1052589681589:ios:8457a3c8f04bc748c447fc',
    messagingSenderId: '1052589681589',
    projectId: 'fragrance-of-mastership',
    storageBucket: 'fragrance-of-mastership.appspot.com',
    iosClientId: '1052589681589-j0np6376p8u9gmtac35056tpo8c7hvv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fragrance',
  );
}
